name: api_reference

on:
  workflow_dispatch:
  pull_request:
    # Only run api_reference action when a header file has been modified.
    paths:
      - '**/lib/include/**.hpp'

jobs:
  doxygen:
    runs-on: ubuntu-22.04
    steps:
      - uses: eProsima/eProsima-CI/external/checkout@v0.2
        with:
          path: src/Fast-DDS-QoS-Profiles-Manager

      - name: Install apt packages
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0.2
        with:
          packages: doxygen cmake libxerces-c-dev

      - name: Install colcon
        uses: eProsima/eProsima-CI/multiplatform/install_colcon@v0.2

      - name: Build library
        uses: eProsima/eProsima-CI/multiplatform/colcon_build@v0.2
        with:
          workspace: src/Fast-DDS-QoS-Profiles-Manager/lib

      - name: Generate documentation
        run: |
          cd src/Fast-DDS-QoS-Profiles-Manager/lib/build/fastdds_qos_profiles_manager_lib/docs
          doxygen doxyfile

      - name: Upload api reference
        uses: actions/upload-artifact@v3
        with:
          name: api_reference
          path: src/Fast-DDS-QoS-Profiles-Manager/lib/build/fastdds_qos_profiles_manager_lib/docs
        if: always()
