name: docs_ci

on:
  workflow_dispatch:
  pull_request:

jobs:
  ubuntu-docs-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: eProsima/eProsima-CI/external/checkout@v0.2
        with:
          path: src/Fast-DDS-QoS-Profiles-Manager

      - name: Install apt packages
        uses: eProsima/eProsima-CI/ubuntu/install_apt_packages@v0.2
        with:
          packages: cmake doxygen libxerces-c-dev

      - name: Install colcon
        uses: eProsima/eProsima-CI/multiplatform/install_colcon@v0.2

      - name: Install GTest
        uses: eProsima/eProsima-CI/multiplatform/install_gtest@v0.2

      - name: Install documentation requirements
        uses: eProsima/eProsima-CI/ubuntu/install_python_packages@v0.2
        with:
          requirements_file_name: src/Fast-DDS-QoS-Profiles-Manager/docs/requirements.txt

      - name: Build workspace
        uses: eProsima/eProsima-CI/multiplatform/colcon_build_test@v0.2
        with:
          packages_names: fastdds_qos_profiles_manager_docs
          cmake_args: -DEPROSIMA_BUILD_TESTS=ON

      - name: Upload documentation
        uses: actions/upload-artifact@v3
        with:
          name: HTML documentation
          path: install/fastdds_qos_profiles_manager_docs/docs/fastdds_qos_profiles_manager_docs/sphinx/html
