name: uncrustify

on:
  workflow_dispatch:
  pull_request:
    # Only run uncrustify action when a source or header file has been modified.
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.h'
      - '**.cxx'

jobs:
  uncrustify:
    runs-on: ubuntu-22.04
    steps:
      - name: eProsima uncrustify
        uses: eProsima/eProsima-CI/ubuntu-22.04/uncrustify@main

      - name: Upload uncrustify results
        uses: actions/upload-artifact@v3
        with:
          name: uncrustify_results
          path: uncrustify_results.xml
        if: always()
